parameters:
    json_placeholder_url: 'https://jsonplaceholder.typicode.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/*/Entity/'
            - '../src/Domain/*/Enum/'
            - '../src/Domain/*/Event/'
            - '../src/Domain/*/ValueObject/'
            - '../src/Kernel.php'

    App\Domain\User\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\User\Persistence\DoctrineUserRepository
