parameters:
    json_placeholder_url: 'https://jsonplaceholder.typicode.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/*/Entity/'
            - '../src/Domain/*/Enum/'
            - '../src/Domain/*/Event/'
            - '../src/Domain/*/ValueObject/'
            - '../src/Kernel.php'

    # User aggregate
    App\Domain\User\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\User\Persistence\DoctrineUserRepository

    App\Application\User\Handler\ImportUsersHandler:
        arguments:
            $defaultUserPassword: '%env(DEFAULT_USER_PASSWORD)%'

    # Task aggregate
    App\Domain\Task\Repository\TaskRepositoryInterface:
        alias: App\Infrastructure\Task\Persistence\DoctrineTaskRepository

    App\Domain\Task\EventStore\EventStoreInterface:
        alias: App\Infrastructure\Task\Persistence\DoctrineEventStore

    # Strategy Pattern - tag all transition strategies
    App\Domain\Task\Strategy\ToInProgressStrategy:
        tags: ['app.task_status_transition_strategy']

    App\Domain\Task\Strategy\ToDoneStrategy:
        tags: ['app.task_status_transition_strategy']

    # Inject tagged strategies into UpdateTaskStatusHandler
    App\Application\Task\Handler\UpdateTaskStatusHandler:
        arguments:
            $strategies: !tagged_iterator app.task_status_transition_strategy
